// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqbqutpuiqwwclyxjeem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxYnF1dHB1aXF3d2NseXhqZWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMzQzMDcsImV4cCI6MjA4MTkxMDMwN30.nSEsBtYD2m9axdkP5CiSqOckVciniT5l1SsAFgvLtYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});